openapi: 3.0.3
info:
  title: Wallet manager
  description: Wallet manager
  version: 1.0.0
servers:
  - url: 'https://www.wallet_manager.com'
paths:
  /user:
  /bank_account:
  /currency:
  /transaction:
components:
  schemas:
    # currency components
    currency_setter:
      type: object
      properties:
        name:
          type: string
        country:
          type: string
      required:
        - name
    currency:
      type: object
      items:
        $ref: '#/components/schemas/currency_setter'
      properties:
        id:
          type: integer
    # user components
    user_setter:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        phone:
          type: string
        email:
          type: string
        password:
          type: string
        currency_id:
          $ref: '#/components/schemas/currency'
      required:
        - password
        - currency_id
    user:
      type: object
      items:
        $ref: '#/components/schemas/user_setter'
      properties:
        id:
          type: integer
    # account components
    account_setter:
      type: object
      properties:
        name:
          type: string
        current_amount:
          type: number
          format: double
        type: # account type
          type: string
        account_number:
          type: string
        user_id:
          $ref: '#/components/schemas/user'
    account:
      type: object
      items:
        $ref: '#/components/schemas/account_setter'
      properties:
        id:
          type: integer
        creation_timestamp:
          type: string
          format: 'date-time'
